(() => {
  'use strict';
  const $ = (s,r=document) => r.querySelector(s);
  const esc = v => String(v ?? '').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const KEY='degajaPreChat';
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{\"topic\":\"\",\"messages\":[]}')}catch(_){return {topic:'',messages:[]}}};
  const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
  function style(){if($('#degajaPreChatStyle'))return;const s=document.createElement('style');s.id='degajaPreChatStyle';s.textContent=`.degaja-prechat{margin:28px auto 0;max-width:900px;padding:24px;background:rgba(255,255,255,.96);border:1px solid rgba(184,147,70,.24);border-radius:24px;box-shadow:0 14px 42px rgba(31,65,95,.07);text-align:left}.degaja-prechat h3{margin:5px 0;color:#18334a;font-size:24px}.degaja-prechat p{color:#687384;line-height:1.6;font-size:14px}.dpc-badge{display:inline-block;padding:6px 10px;border-radius:999px;background:#eef5fa;color:#18334a;font-size:11px;font-weight:800}.dpc-messages{height:230px;overflow:auto;background:#f6f9fb;border-radius:18px;padding:14px;margin:15px 0}.dpc-msg{padding:10px 13px;border-radius:15px;margin:8px 0;max-width:84%;font-size:14px;line-height:1.5}.dpc-msg.bot{background:#fff;border:1px solid #e3e9ee}.dpc-msg.user{background:#18334a;color:#fff;margin-left:auto}.dpc-row{display:flex;gap:8px}.dpc-row input{flex:1;border:1px solid #d7e0e6;border-radius:999px;padding:12px 15px;outline:0}.dpc-row button,.dpc-action{border:0;border-radius:999px;padding:12px 18px;background:#18334a;color:#fff;font-weight:800;cursor:pointer}.dpc-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:13px}.dpc-actions .gold{background:#b88a32}.dpc-note{font-size:11px!important;color:#8a91a0!important;margin-top:12px}.dpc-loading{opacity:.65}.dpc-topic{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.dpc-topic button{border:1px solid #dfe7ed;background:#fff;border-radius:999px;padding:8px 12px;color:#18334a;cursor:pointer}.dpc-topic button.active{border-color:#b88a32;background:#f6edda}`;document.head.appendChild(s)}
  function render(){const old=$('#degajaPreChat');if(old)return;const wrap=$('#human .human-wrap');if(!wrap)return;const state=load();const el=document.createElement('div');el.id='degajaPreChat';el.className='degaja-prechat';el.innerHTML=`<span class="dpc-badge">💬 VORAB-CHAT · ANONYM</span><h3>Erzähl uns zuerst, was dich bewegt.</h3><p>Du kannst dein Thema hier anonym vorab schildern. DEGAJA hilft dir, deine Gedanken zu ordnen. Wenn du danach persönlich sprechen möchtest, kannst du direkt zur bezahlten Live-Beratung wechseln.</p><div class="dpc-topic"><button data-topic="Liebe & Beziehung">❤️ Liebe</button><button data-topic="Beruf & Karriere">💼 Beruf</button><button data-topic="Zukunft">✨ Zukunft</button><button data-topic="Etwas anderes">🌙 Etwas anderes</button></div><div class="dpc-messages" id="dpcMessages"></div><div class="dpc-row"><input id="dpcInput" maxlength="600" placeholder="Schreib hier ganz offen …"><button id="dpcSend">Senden</button></div><div class="dpc-actions"><button class="dpc-action gold" id="dpcVoice">🎧 Persönlich weitergehen</button><button class="dpc-action" id="dpcClear">Chat zurücksetzen</button></div><p class="dpc-note">Dieser Vorab-Chat ist kein Telefonat. Für die Live-Sprachberatung wird eine Zahlung bzw. ein vorhandenes Live-Guthaben benötigt. Deine private Telefonnummer wird nicht angezeigt.</p>`;wrap.appendChild(el);const msgs=$('#dpcMessages');function draw(){msgs.innerHTML='';if(!state.messages.length)msgs.innerHTML='<div class="dpc-msg bot">Hallo. Ich bin DEGAJA. Was beschäftigt dich gerade? Du kannst hier anonym anfangen.</div>';state.messages.forEach(m=>msgs.insertAdjacentHTML('beforeend',`<div class="dpc-msg ${m.role==='user'?'user':'bot'}">${esc(m.text).replace(/\n/g,'<br>')}</div>`));msgs.scrollTop=msgs.scrollHeight}draw();el.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{state.topic=b.dataset.topic;el.querySelectorAll('[data-topic]').forEach(x=>x.classList.remove('active'));b.classList.add('active');save(state);});
    async function send(){const input=$('#dpcInput'),text=input.value.trim();if(!text)return;state.messages.push({role:'user',text});save(state);draw();input.value='';const typing=document.createElement('div');typing.className='dpc-msg bot dpc-loading';typing.id='dpcTyping';typing.textContent='DEGAJA denkt nach …';msgs.appendChild(typing);msgs.scrollTop=msgs.scrollHeight;try{const history=state.messages.slice(-8).map(m=>`${m.role==='user'?'Kunde':'DEGAJA'}: ${m.text}`).join('\n');const r=await fetch('/api/oracle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:history,topic:state.topic||'persönliches Anliegen',mode:'free'})});const d=await r.json();const answer=r.ok&&d.text?d.text:'Ich höre dir zu. Beschreibe gern noch etwas genauer, was dich beschäftigt.';state.messages.push({role:'bot',text:answer});save(state);$('#dpcTyping')?.remove();draw()}catch(_){$('#dpcTyping')?.remove();state.messages.push({role:'bot',text:'Ich bin hier. Erzähl mir gern noch etwas zu deinem Thema.'});save(state);draw()}}
    $('#dpcSend').onclick=send;$('#dpcInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();send()}};$('#dpcClear').onclick=()=>{state.topic='';state.messages=[];save(state);draw()};$('#dpcVoice').onclick=()=>{const live=$('#degajaLiveConsult');if(live){live.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>$('#degajaLiveStart')?.click(),350)}else document.querySelector('#human')?.scrollIntoView({behavior:'smooth'})};}
  function init(){style();render()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
